version: '2.18.1'

networks:
  dev:
    driver: bridge

services:
  dotnet-rpg2:
    image: docker.io/library/dotnetrpg2
    depends_on:
      - "app_db"
    container_name: dotnetrpg2-services
    ports:
      - "8088:80"
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__PostgresConnection=Username=postgres;Password=37839603;Server=app_db;Port=5432;Database=dotnet-rpg2;IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev
    
  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=37839603
      - POSTGRES_DB=dotnet-rpg2 
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data 
    networks:
      - dev
volumes:
  app_data:


